config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
    
  resources :users, only: [:show]
  
  resources :posts, only: [:index, :show, :create, :destroy] do
    resources :photos, only: [:create]
    resources :likes, only:[:create, :destroy, :index, :show, :new, :edit, :update], shallow: true
    resources :comments, only:[:index, :create, :destroy], shallow: true
    resources :bookmarks, only: [:create, :destroy], shallow: true
  end
     
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> {order(:created_at => :desc)}, dependent: :destroy
  has_many :comments, ->{order(:created_at => :desc)}, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  
  def is_belongs_to? user
    Post.find_by(user_id: user.id, id: id)
  end
  
  def is_liked user
    Like.find_by(user_id: user.id, post_id: id)
  end  
  
  def is_bookmarked user
    Bookmark.find_by(user_id: user.id, post_id: id)
  end  

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_post, only: [:show, :destroy]
    
    
    
    def index
       @posts =Post.all.limit(10).includes(:photos, :user, :likes).
       order('created_at desc') 
       @post = Post.new
    end
      
      
    def create
       @post = current_user.posts.build(post_params) 
         if @post.save
           if params[:images]
               params[:images].each do |img|
                   @post.photos.create(image: img)
               end
           end
           
           redirect_to posts_path
           flash[:notice] = "Saved..."
           
        else
            flash[:alert] = "Something went wrong..."
            redirect_to posts_path
         end
    end 
    
    
    def show
        @photos = @post.photos
        @likes = @post.likes.includes(:user)
        @comment = Comment.new
        @is_likes = @post.is_liked(current_user)
        @is_bookmarked = @post.is_bookmarked(current_user)
    end
    
    def destroy
        if @post.user == current_user
            if @post.destroy
             flash[:notice] = "Post deleted!"
           else
            flash[:alert] = "Something went wrong ..."
            end
        else
            flash[:notice] = "You don't have permission to do that"
        end
        redirect_to root_path
        
    end
    

    private
    
    
    def find_post
        @post = Post.find_by(id: params[:id])
        
        return if @post
        flash[:danger] = "Post not exist!"
        redirect_to root_path
        
    end

    def post_params
        params.require(:post).permit (:content)
    end


end

app/views/posts/_bookmark_icon.html.erb
<% if is_bookmarked.present? %>
  <%= link_to "Bookmarked", bookmark_path(is_bookmarked), method: :delete, remote: true,
   class: "core-sprite bookmarked hide-text" %>
   
<% else %>
  <%= link_to "Bookmark", post_bookmarks_path(post), method: :post, 
  remote: true, class: "core-sprite bookmark hide-text" %>
<% end %>

app/views/posts/_comment_form.html.erb
 <%= form_for [post, Comment.new], :html => {:class => "w-100"}, remote: true do |f| %>
   <%= f.hidden_field :user_id, value: current_user.id %>
   <%= f.hidden_field :post_id, value: post.id %>
   <%= f.text_field :content, class: "form-control comment-input border-0",
   placeholder: "Add a comment ...", autocomplete: :off %>
   
 <% end %>
 

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
 <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "Delete comment", comment_path(comment),
      method: :delete, remote: true, class: "core-sprite delete-comment hide-text" %>
    <% end %>
    <span><strong><%= comment.user.name %></strong></span>
    <span><%= comment.content %></span>
 </div>

<% end %>

app/views/posts/_like_icon.html.erb
<% if is_liked.present? %>
 <%= link_to "Love", like_path(is_liked), method: :delete, remote: true,
   class: "core-sprite loved hide-text"%>
 <% else %>
  <%= link_to "Loved", post_likes_path(post), method: :post, remote: true,
    class: "core-sprite love hide-text"%>
 <% end %> 

app/views/posts/_like_text.html.erb
<% likes.each.with_index do |like, index| %>
<strong>
      <% if likes.size == 1 %>
       <%= like.user.name %></strong> likes this
      <% elsif like == likes.last %>
       </strong>and<strong>
         <%= + like.user.name %></strong> like this
      <% elsif index > 1 %>
       </strong><%= "and" +(likes.size-index).to_s + "others" %> like this
       <% break %>
      <% elsif index==likes.size-2 || index ==1 %>
       <%= like.user.name %>
      <% else %> 
       <%= like.user.name + "," %>
      <% end %> 
<% end %> 
</strong>

app/views/posts/_photos.html.erb
<% if post.photos.size == 1 %>
  <%= image_tag post.photos.first.image.url(:standard), class:"card-img-top" %>
<% else %>
  <div class="carousel slide" data-ride ="carousel" id="carousel-post-<%= @post.id %>">
    <div class="carousel-inner">
        　<% post.photos.each do |photo| %>
        　  <% if photo == post.photos.first %>
                 <div class="carousel-item active">
           <% else %>
                 <div class="carousel-item">
           <% end %>
                <%= image_tag photo.image.url(:standard), class: "card-img-top" %>
          </div>
         <% end %>
　　  </div>
      
    <a class="carousel-control-prev" href="#carousel-post-<%= @post.id %>" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-post-<%= @post.id %>" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>   
   </div>
  <% end %>                

app/views/posts/_posts_list.html.erb
<% @posts.each do |post| %>
<div class="card mt-3 post">
    <div class="card-header d-flex align-items-center">
        <%= link_to user_path(post.user), class: "no-text-decoration" do %>
          <%= image_tag avatar_url(post.user), class: "post-author-icon" %>
      <% end %> 
      <%= link_to user_path(post.user), class: "normal-color no-text-decoration",
        title: post.user.name do %>
        <strong><%= post.user.name %></strong>
       <% end %>    
       
       <% if post.is_belongs_to? current_user %>
         <%= link_to post_path(post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %> 
           <i class="far fa-trash-alt" aria-hidden="true"></i>
         <% end %>
       <% end %>     
    </div>
    
   <%= render "photos", {post: post} %>
   
    
    <div class="card-body">
        <div class="row actions">
         <div id="like-icon-post-<%= post.id.to_s %>">
        <%= render "like_icon", {is_liked: post.is_liked(current_user), post: post} %>   
         </div>   

             
            <a href="#" class="core-sprite comment hide-text">Comment</a>
            <div id="bookmark-icon-post-<%= post.id.to_s %>" class ="ml-auto">
                <%= render "bookmark_icon", {is_bookmarked: post.is_bookmarked(current_user), post:post} %>
            </div>

           
        </div>
        
        
        <div id = "like-text-post-<%=post.id.to_s %>">
        <%= render "like_text", {likes: post.likes} %>

        </div>
        <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.content %></span>
        </div>
        <div id="comment-post-<%= post.id.to_s %>">
            <%= render "comment_list", {post: post} %>
        </div>
        <div class="light-color post-time"><%= time_ago_in_words(post.created_at).upcase %> AGO</div>
         <%= link_to "ABOUT", post_path(post), class: "light-color post-time no-text-decoration"%>
        <hr>
        <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
         <%= render "comment_form", {post: post} %>
        </div>
    </div>
 </div>
<% end %> 

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
    <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
        <div class="card">
            <div class="card-header">
                Create Post
            </div>
            <div class="card-body">
              <%= form_for @post, :html => {:multipart => true, :class => "dropzone upload-images p-0 border-0"} do |f| %>
                <div class="form-group row mt-2">
                    <div class="col-auto pr-0">
                        <%= image_tag avatar_url(current_user), class: "post-author-icon" %>
                    </div>
                    <div class="col pl-0">
                       <%= f.text_field :content, class: "form-control border-0",
                       placeholder: "Say something about this ..." %>
                    </div>
                </div>
                 <div class="fallback">
                 <%= file_field_tag "images[]", type: :file, multiple: true %>
                 </div> 
                  <div class="dz-message m-0"></div>
                  <div class="dropzone-previews mb-3">
                    <div class="upload-photos-icon">
                        <i class="fa fa-plus fa-2x" aria-hidden ="true" style="color:#dddfe2"></i>
                    </div>
                  </div>
                 
                 <%= f.submit "Post", class: "btn btn-primary" %>
              <% end %>
            </div>
        </div>
        
        
        <div class="posts">
            <%= render 'posts_list' %>
        </div>
    </div>
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-itms-center mt-3">
    <div class="row post box col-xl-10 col-lg-11 col-xs-12">
        <div class="col-lg-8 col-md-7 px-0 d-flex post-show-img">
            <div class="align-self-center">
             <%= render "photos", {post: @post} %>
            </div>
        </div>
        <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0">
            <div class="row px-3 d-flex align-items-center">
                <%= link_to user_path(@post.user), class:"no-text-decoration" do %>
                <%= image_tag avatar_url(@post.user), class: "post-author-icon" %>
              <% end %>
              <%= link_to user_path(@post.user), class: "normal-color no-text-decoration d-flex align-self-center",
                title: @post.user.name do %>
                <strong><%= @post.user.name %></strong>
              <% end %>
              
               <% if @post.is_belongs_to? current_user %>                 
                 <%= link_to post_path(@post), method: :delete, class: "ml-auto delete-post-icon mx-0 my-auto" do %> 
                  <i class="far fa-trash-alt" aria-hidden="true"></i>
                <% end %>
              <% end %>
              
            </div>
            <hr class="mb-0">
            <div class="comment-list py-2">
                <% if @post.content.present? %>
                <div>
                    <span><strong><%= @post.user.name %></strong></span>
                    <span><%= @post.content %></span>
                </div>
                <% end %>
                <!--load comment-->
                <div id="comment-post-<%= @post.id.to_s %>">
                  <%= render "comment_list", {post: @post } %>
                </div>
             
             
            </div>
            <hr class="mt-0">
            
                 <div class="row actions">
                    <div id="like-icon-post-<%= @post.id.to_s %>">
                     <%= render "like_icon", {is_liked: @is_likes, post: @post} %>   
                    </div>  
                    <a href="#" class="core-sprite comment hide-text">Comment</a>
                    
                      <div id="bookmark-icon-post-<%= @post.id.to_s %>" class="ml-auto">
                       <%= render "bookmark_icon", {is_bookmarked: @is_bookmarked, post: @post} %>
                       </div> 
                       
                </div>
                    <div id = "like-text-post-<%=@post.id.to_s %>">
                    <%= render "like_text", {likes: @likes} %>

                   </div>
                <div class="light-color post-time"><%= time_ago_in_words(@post.created_at).upcase %> AGO</div>
         
                <hr>
                <div class="row actions" id="comment-form-post-<%= @post.id.to_s %>">
                <%= render "comment_form", {post: @post} %>
                </div>           
            
            </hr>
        </div>
    </div>
</div>